### ISSUE TITLE
How to set `:Logsitter javascript` for filetypes of .svelte and .vue?

### ISSUE THREAD

**Issue by lsshawn** [gaelph/logsitter.nvim#3]
When I tried to use it on '.svelte' files, it says 'No logger for svelte'.

Is there a way to override this?

Or to treat .svelte files as javascript?

**Comment by gaelph** [comment]
Hi !

I got this working in svelte files by creating `svelte.lua` file in `$NVIM_CONFIG/after/ftplugin` containing:
```lua
local logsitter = require("logsitter")

-- Register the javascript logger as the one to use with `svelte` files
logsitter.register(require("logsitter.lang.javascript"), { "svelte" })

vim.keymap.set("n", "<leader>lg", function()
	require("logsitter").log()
end)
```

You can do some thing similiar for `vue` files.

Obviously, feel free to use the keymap that suites you best !

**Comment by lsshawn** [comment]
Thanks a lot.

This is one of the VSCode plugin I missed a lot. I even [asked in Reddit years ago](https://www.reddit.com/r/vim/comments/dmj7wr/turbo_console_log_plugin_for_vim/).
